# Only built-in gzip/xz decompression and tar/zip readers are used by dotcmd.
set(BUILD_SHARED_LIBS OFF CACHE BOOL "")
set(BUILD_TESTING OFF CACHE BOOL "")
set(ENABLE_ZLIB ON CACHE BOOL "")
set(ENABLE_LZMA ON CACHE BOOL "")
foreach(feature MBEDTLS NETTLE OPENSSL LIBB2 LZ4 LZO ZSTD BZip2 LIBXML2 EXPAT
        WIN32_XMLLITE PCREPOSIX PCRE2POSIX LIBGCC CNG TAR CPIO CAT UNZIP
        XATTR ACL ICONV TEST INSTALL)
    set(ENABLE_${feature} OFF CACHE BOOL "")
endforeach()
set(CMAKE_DISABLE_FIND_PACKAGE_PkgConfig ON CACHE BOOL "")
