local S = require("dotcmd.schema")
local L = require("dotcmd.luals")

-- Exercise the private generator without exposing it in the module API.
local generate
for i = 1, math.huge do
    local name, value = debug.getupvalue(L.setup, i)
    if not name then break end
    if name == "generate" then generate = value; break end
end
assert(generate)

local function setup_project(name)
    local path = host.project_dir .. "/" .. name
    fs.mkdir(path)
    t.write(path .. "/.cmd", "")
    return path
end

test("setup creates portable managed configuration and regenerates declarations", function()
    local project = setup_project("managed")
    t.success(t.run_project(project, "--setup", "luals"))
    local config = json.decode(t.read(project .. "/.luarc.json"))
    assert(config["$dotcmd"] == true and config.runtime.version == "Lua 5.5")
    assert(config.runtime.path[1] == "?.lua" and config.runtime.path[2] == "?/init.lua")
    assert(config.runtime.pathStrict == true)
    assert(config.workspace.library == nil)
    assert(config.workspace.ignoreDir[1] == "target" and config.workspace.ignoreDir[2] == ".git")
    assert(config.workspace.checkThirdParty == "Disable")
    local generated = t.read(project .. "/.cmd.d.lua")
    assert(generated:find("-- Generated by .cmd --setup luals; do not edit.\n---@meta\n", 1, true) == 1)
    assert(generated:find("function fetch", 1, true))
    t.write(project .. "/.cmd.d.lua", "old declarations")
    t.write(project .. "/.luarc.json", '{"$dotcmd":true,"runtime.version":"Lua 5.1"}')
    t.success(t.run_project(project, "--setup", "luals"))
    assert(t.read(project .. "/.cmd.d.lua") == generated)
    assert(json.decode(t.read(project .. "/.luarc.json")).runtime.version == "Lua 5.5")
end)

test("setup preserves unmanaged configuration and annotations", function()
    for i, config in ipairs { '{}', '{"$dotcmd":false}', '{"$dotcmd":"true"}' } do
        local project = setup_project("unmanaged-" .. i)
        t.write(project .. "/.luarc.json", config)
        t.write(project .. "/.cmd.d.lua", "user declarations")
        t.failure(t.run_project(project, "--setup", "luals"), "unmanaged .luarc.json")
        assert(t.read(project .. "/.luarc.json") == config)
        assert(t.read(project .. "/.cmd.d.lua") == "user declarations")
    end
end)

test("setup preserves an existing annotation file without managed configuration", function()
    local project = setup_project("occupied")
    t.write(project .. "/.cmd.d.lua", "user declarations")
    t.failure(t.run_project(project, "--setup", "luals"), "existing .cmd.d.lua")
    assert(t.read(project .. "/.cmd.d.lua") == "user declarations")
    assert(not fs.stat(project .. "/.luarc.json"))
end)

test("setup does not shadow existing JSONC configuration", function()
    local project = setup_project("jsonc")
    t.write(project .. "/.luarc.jsonc", "{ /* user configuration */ }")
    t.failure(t.run_project(project, "--setup", "luals"), "existing .luarc.jsonc")
    assert(t.read(project .. "/.luarc.jsonc") == "{ /* user configuration */ }")
    assert(not fs.stat(project .. "/.luarc.json") and not fs.stat(project .. "/.cmd.d.lua"))
end)

local function contains(text, expected)
    assert(text:find(expected, 1, true), "missing declaration: " .. expected .. "\n" .. text)
end

local function signature(params, returns)
    return { params = S.table { fields = params }, returns = S.table { fields = returns or {} } }
end

test("primitives, literals, unions and maps describe input types", function()
    local schema = S.registry {
        definitions = {
            Count = S.integer(), Nothing = S.null(), Flag = S.boolean(), Number = S.number(),
            Handle = S.file(),
            Labels = S.map { key = S.string(), value = S.array { items = S.string() } },
            Choice = S.union { alternatives = { S.literal { value = "a\nb" }, S.literal { value = false }, S.null() } },
        },
        schema = S.table { fields = { labels = S.ref { name = "Labels" } } },
    }
    local text = generate(schema)
    contains(text, "---@alias Count integer")
    contains(text, "---@alias Number number")
    contains(text, "---@alias Flag boolean")
    contains(text, "---@alias Nothing nil")
    contains(text, "---@alias Handle file*")
    contains(text, "---@alias Choice \"a\\nb\"|false|nil")
    contains(text, "---@alias Labels table<string, string[]>")
    contains(text, "---@type Labels\nlabels = nil")
    assert(load(text))
end)

test("mixed tables retain positions, required values and optional defaults", function()
    local text = generate(S.registry {
        definitions = { Options = S.table { fields = {
            { "program", S.string() }, { "args", S.number(), arity = "*" },
            mode = S.string { default = "fast", description = "Execution mode." },
            enabled = S.boolean { default = false },
            name = S.optional { schema = S.string() },
            ["odd key"] = S.integer(),
        } } },
        schema = S.table { fields = {} },
    })
    contains(text, "---@class (exact) Options")
    contains(text, "---@field [1] string")
    contains(text, "---@field [integer] number")
    contains(text, "---@field mode? string Execution mode. Default: \"fast\".")
    contains(text, "---@field enabled? boolean Default: false.")
    contains(text, "---@field name? string")
    contains(text, "---@field [\"odd key\"] integer")
end)

test("forward and recursive references remain named", function()
    local text = generate(S.registry {
        definitions = {
            Node = S.table { fields = { children = S.array { items = S.ref { name = "Node" } } } },
            RecursiveArray = S.array { items = S.ref { name = "RecursiveArray" } },
            RecursiveUnion = S.union { alternatives = { S.ref { name = "RecursiveUnion" }, S.string() } },
            Names = S.array { items = S.ref { name = "Name" } }, Name = S.string(),
        },
        schema = S.table { fields = { node = S.ref { name = "Node" }, union = S.ref { name = "RecursiveUnion" } } },
    })
    contains(text, "---@field children Node[]")
    contains(text, "---@alias RecursiveArray RecursiveArray[]")
    contains(text, "---@alias Names Name[]")
    contains(text, "---@alias RecursiveUnion RecursiveUnion|string")
    assert(text == generate(S.registry {
        definitions = {
            Names = S.array { items = S.ref { name = "Name" } }, Name = S.string(),
            RecursiveArray = S.array { items = S.ref { name = "RecursiveArray" } },
            RecursiveUnion = S.union { alternatives = { S.ref { name = "RecursiveUnion" }, S.string() } },
            Node = S.table { fields = { children = S.array { items = S.ref { name = "Node" } } } },
        },
        schema = S.table { fields = { node = S.ref { name = "Node" }, union = S.ref { name = "RecursiveUnion" } } },
    }))
end)

test("nested registries shadow locally and preserve outer references", function()
    local nested = S.registry {
        definitions = { Name = S.integer() },
        schema = S.table { fields = { local_name = S.ref { name = "Name" }, outer = S.ref { name = "Outer" } } },
    }
    local text = generate(S.registry {
        definitions = { Name = S.string(), Outer = S.boolean(), ["Scope1.Name"] = S.number() },
        schema = S.table { fields = { nested = nested, name = S.ref { name = "Name" } } },
    })
    contains(text, "---@alias Scope1.Name number")
    contains(text, "---@alias Scope1.Name_2 integer")
    contains(text, "---@type { local_name: Scope1.Name_2, outer: Outer }")
    contains(text, "---@type Name\nname = nil")
end)

test("non-record roots get an alias without colliding with definitions", function()
    local text = generate(S.registry {
        definitions = { Value = S.string() }, schema = S.ref { name = "Value" },
    })
    contains(text, "---@alias Value string")
    contains(text, "---@alias Value_2 string")
end)

test("global overloads preserve argument lists and repeated results", function()
    local text = generate(S.table { fields = {
        call = S.func { description = "Call a program.", signatures = {
            signature({ { "options", S.table { fields = { path = S.string() } } } }, { { "result", S.boolean() } }),
            signature({ { "program", S.string() }, { "arguments", S.string(), arity = "*" } }, { { "result", S.boolean() } }),
        } },
        many = S.func { signatures = { signature({ { "values", S.integer(), arity = "+" } }, {
            { "first", S.string() }, { "more", S.any(), arity = "*" },
        }) } },
    } })
    contains(text, "---Call a program.\n---@overload fun(program: string, ...: string): boolean")
    contains(text, "---@param options { path: string }")
    contains(text, "function call(options) end")
    contains(text, "---@param values integer\n---@param ... integer")
    contains(text, "---@return string first\n---@return any ...")
    contains(text, "function many(values, ...) end")
end)

test("named alternatives describe input shapes rather than conformed tags", function()
    local text = generate(S.table { fields = {
        parse = S.func { signatures = { {
            params = S.alt { alternatives = {
                { "text", S.table { fields = { { "text", S.string() } } } },
                { "number", S.table { fields = { { "value", S.number() } } } },
            } },
            returns = S.table { fields = { { "value", S.optional { schema = S.string() }, arity = "?" } } },
        } } },
    } })
    contains(text, "---@overload fun(value: number): string|nil")
    contains(text, "---@param text string")
    contains(text, "---@return string|nil value")
    assert(not text:find("tag", 1, true))
end)

test("literal meanings and per-use reference descriptions survive generation", function()
    local text = generate(S.registry {
        definitions = {
            Mode = S.union { alternatives = {
                S.literal { value = "skip", description = "Keep existing output." },
                S.literal { value = "replace", description = "Publish new output.\nPreserve permissions." },
            } },
            Run = S.func { signatures = { signature({}) }, description = "Generic function." },
        },
        schema = S.table { fields = {
            run = S.ref { name = "Run", description = "Run this task." },
            mode = S.ref { name = "Mode" },
        } },
    })
    contains(text, "---@alias Mode\n---| \"skip\" # Keep existing output.")
    contains(text, "---| \"replace\" # Publish new output.<br>Preserve permissions.")
    contains(text, "---Run this task.\nfunction run() end")
    contains(text, "---@type Mode\nmode = nil")
    assert(not text:find("---Keep existing output.\n---@type Mode", 1, true))
end)

test("generation neither executes callbacks nor changes schemas", function()
    local calls = 0
    local schema = S.table { fields = { name = S.string { description = "Name.", validate = function()
        calls = calls + 1
        error("must not run")
    end } } }
    local field = schema.fields.name
    local first = generate(schema)
    assert(first == generate(schema) and calls == 0)
    assert(schema.fields.name == field and field.type == "string" and field.validate)
    for key in pairs(field) do assert(key == "type" or key == "description" or key == "validate") end
end)

test("full API emits every public global and preserves schema contracts", function()
    local api = require("dotcmd.api")
    local text = generate(api)
    for name, schema in pairs(api.schema.fields) do
        if schema.type == "function" then contains(text, "function " .. name .. "(")
        else contains(text, name .. " = nil") end
    end
    contains(text, "---@overload fun(url: string, sha256: string): string")
    contains(text, "---@param command Command|ExecCommand")
    contains(text, "---@param command Command|SpawnCommand")
    contains(text, "---@field body? string|any Binary-safe response string by default")
    contains(text, "---@field stdin file* Present when stdin is piped.")
    contains(text, "---@field stdout file* Present when stdout is piped.")
    contains(text, "---@field stderr file* Present when stderr is piped.")
    assert(not text:find("FileHandle", 1, true))
    contains(text, "---@field stdout string Present when captured.")
    contains(text, "---@field stderr string Present when captured.")
    contains(text, "---@field check? any False disables HTTP status checking;")
    assert(not text:find("Format", 1, true))
    assert(not text:find("dotcmd%.[A-Z]"))
    assert(load(text))
end)

test("named children emit inheritance and only their own fields", function()
    local schema = S.registry {
        definitions = {
            Parent = S.table { fields = { name = S.string { description = "Parent name." }, count = S.integer() } },
            Child = S.table { extends = S.ref { name = "Parent" }, fields = { count = S.string(), enabled = S.boolean() } },
            Grandchild = S.table { extends = S.ref { name = "Child" }, fields = {} },
        },
        schema = S.table { fields = {} },
    }
    local text = generate(schema)
    contains(text, "---@class (exact) Child: Parent\n---@field count string\n---@field enabled boolean\n\n")
    contains(text, "---@class (exact) Grandchild: Child\n\n")
    contains(text, "---@class (exact) Parent\n---@field count integer\n---@field name string Parent name.")
    assert(schema.definitions.Child.fields.name == nil)
end)

test("anonymous inherited records and signatures preserve reference scopes", function()
    local text = generate(S.registry {
        definitions = {
            Value = S.string(),
            Parent = S.table { fields = { name = S.ref { name = "Value" } } },
            Params = S.table { fields = { { "text", S.ref { name = "Value" } } } },
        },
        schema = S.registry {
            definitions = {
                Value = S.integer(),
                Child = S.table { extends = S.ref { name = "Parent" }, fields = { number = S.ref { name = "Value" } } },
            },
            schema = S.table { fields = {
                child = S.table { extends = S.ref { name = "Parent" }, fields = { number = S.ref { name = "Value" } } },
                run = S.func { signatures = { {
                    params = S.table { extends = S.ref { name = "Params" }, fields = {} },
                    returns = S.table { extends = S.ref { name = "Params" }, fields = {} },
                } } },
            } },
        },
    })
    contains(text, "---@class (exact) Scope1.Child: Parent\n---@field number Scope1.Value")
    contains(text, "---@type { name: Value, number: Scope1.Value }")
    contains(text, "---@param text Value\n---@return Value text\nfunction run(text) end")
end)

test("inherited roots expose inherited globals", function()
    local text = generate(S.registry {
        definitions = { Parent = S.table { fields = { inherited = S.string() } } },
        schema = S.table { extends = S.ref { name = "Parent" }, fields = { own = S.integer() } },
    })
    contains(text, "---@type string\ninherited = nil")
    contains(text, "---@type integer\nown = nil")
end)
