# Generated by dotcmd. This adapter queries the launcher being completed.
function __dotcmd_hex
    set -l encoded (printf '%s' "$argv[1]" | od -An -v -tx1 | string replace -ar '\s' '' | string join '')
    if test -n "$encoded"
        printf '%s\n' "$encoded"
    else
        printf '%s\n' -
    end
end

function __dotcmd_unhex
    if test "$argv[1]" = -
        return
    end
    string match -qr '^([0-9a-f]{2})+$' -- "$argv[1]"; or return 1
    printf '%b' (string replace -ar '(..)' '\\\\x$1' -- "$argv[1]")
end

function __dotcmd_complete
    set -l words (commandline -xpc)
    test (count $words) -gt 0; or return
    set -l current (commandline -ct)
    set -l request words (__dotcmd_hex (commandline -xct))
    for word in $words[2..-1]
        set -a request (__dotcmd_hex "$word")
    end
    for line in (command "$words[1]" --complete $request 2>/dev/null)
        set -l fields (string split \t -- "$line")
        test (count $fields) -eq 3; or continue
        switch $fields[1]
            case dotcmd:value
                set -l value (__dotcmd_unhex "$fields[2]")
                set -l description (__dotcmd_unhex "$fields[3]")
                printf '%s\t%s\n' "$value" "$description"
            case dotcmd:file dotcmd:directory
                set -l matches (complete -C "'' $current")
                for match in $matches
                    if test "$fields[1]" = dotcmd:directory
                        string match -qr '/$' -- "$match"; or continue
                    end
                    printf '%s\n' "$match"
                end
        end
    end
end

complete -c .cmd -f -a '(__dotcmd_complete)'
