# Generated by dotcmd. This adapter queries the launcher being completed.
_dotcmd_hex() {
    local LC_ALL=C text=$1 i byte
    REPLY=
    for ((i=0; i<${#text}; i++)); do
        printf -v byte '%d' "'${text:i:1}"
        printf -v byte '%02x' "$((byte & 255))"
        REPLY=$REPLY$byte
    done
    [[ -n $REPLY ]] || REPLY=-
}

_dotcmd_unhex() {
    local text=$1 i escaped=
    REPLY=
    [[ $text == - ]] && return
    [[ $text != *[!0-9a-f]* && $((${#text} % 2)) == 0 ]] || return 1
    for ((i=0; i<${#text}; i+=2)); do escaped="$escaped\\x${text:i:2}"; done
    printf -v REPLY '%b' "$escaped"
}

# Quote text ourselves: Readline's filenames mode also adds '/' to enum
# values that happen to name directories. Bash 3.2 cannot toggle that mode.
_dotcmd_quote() {
    local text=$1 quote=$2 i char
    REPLY=
    for ((i=0; i<${#text}; i++)); do
        char=${text:i:1}
        case $quote in
            "'") [[ $char != "'" ]] || char="'\\''" ;;
            '"') case $char in '\'|'"'|'$'|'`') char=\\$char ;; esac ;;
            *) case $char in
                $'\n') char="'$char'" ;;
                [[:space:]]|'\'|'"'|"'"|'$'|'`'|'&'|';'|'|'|'<'|'>'|'('|')'|'{'|'}'|'['|']'|'*'|'?'|'!'|'#'|'~') char=\\$char ;;
            esac ;;
        esac
        REPLY=$REPLY$char
    done
}

_dotcmd_complete() {
    local LC_ALL=C REPLY request breaks kind a b trim= quote= candidate before partial match expanded suffix
    COMPREPLY=()
    _dotcmd_hex "${COMP_LINE:0:COMP_POINT}"
    request=$REPLY
    _dotcmd_hex "$COMP_WORDBREAKS"
    breaks=$REPLY
    while IFS=$'\t' read -r kind a b; do
        case $kind in
            dotcmd:quoting)
                _dotcmd_unhex "$a" || continue
                trim=$REPLY
                _dotcmd_unhex "$b" || continue
                quote=$REPLY
                ;;
            dotcmd:value)
                _dotcmd_unhex "$a" || continue
                candidate=${REPLY#"$trim"}
                _dotcmd_quote "$candidate" "$quote"
                # Readline closes an open quote itself.
                [[ -n $quote ]] || REPLY="$REPLY "
                COMPREPLY+=("$REPLY")
                ;;
            dotcmd:file|dotcmd:directory)
                _dotcmd_unhex "$a" || continue
                before=$REPLY
                _dotcmd_unhex "$b" || continue
                partial=$REPLY
                expanded=$partial
                [[ $partial == '~/'* ]] && expanded=$HOME/${partial:2}
                local action=-f
                [[ $kind == dotcmd:directory ]] && action=-d
                while IFS= read -r match; do
                    suffix=
                    if [[ -d $match ]]; then match=${match%/}/
                    elif [[ -z $quote ]]; then suffix=' '; fi
                    candidate=$before$match
                    _dotcmd_quote "${candidate#"$trim"}" "$quote"
                    COMPREPLY+=("$REPLY$suffix")
                done < <(compgen "$action" -- "$expanded")
                ;;
        esac
    done < <("$1" --complete bash "$request" "$breaks" 2>/dev/null)
    return 0
}

complete -o nospace -F _dotcmd_complete .cmd
