# Generated by dotcmd. This adapter queries the launcher being completed.
_dotcmd_hex() {
    local LC_ALL=C text=$1 byte
    integer i
    REPLY=
    for ((i=1; i<=${#text}; i++)); do
        printf -v byte '%02x' "'$text[i]"
        REPLY+=$byte
    done
    [[ -n $REPLY ]] || REPLY=-
}

_dotcmd_unhex() {
    local text=$1 escaped=
    integer i
    REPLY=
    [[ $text == - ]] && return
    [[ $text != *[^0-9a-f]* && $((${#text} % 2)) == 0 ]] || return 1
    for ((i=1; i<=${#text}; i+=2)); do escaped+="\\x${text[i,i+1]}"; done
    printf -v REPLY '%b' "$escaped"
}

_dotcmd_complete() {
    local REPLY kind a b item before path_kind launcher=${(Q)words[1]}
    local -a request candidates descriptions
    integer i
    [[ $launcher == */* ]] || launcher=${commands[$launcher]:-$launcher}
    _dotcmd_hex "${(Q)PREFIX}"
    request=(words "$REPLY")
    for ((i=2; i<CURRENT; i++)); do
        _dotcmd_hex "${(Q)words[i]}"
        request+=("$REPLY")
    done
    while IFS=$'\t' read -r kind a b; do
        case $kind in
            dotcmd:value)
                _dotcmd_unhex "$a" || continue
                candidates+=("$REPLY")
                item=$REPLY
                _dotcmd_unhex "$b" || continue
                descriptions+=("$item${REPLY:+  $REPLY}")
                ;;
            dotcmd:file|dotcmd:directory)
                _dotcmd_unhex "$a" || continue
                before=$REPLY
                path_kind=$kind
                ;;
        esac
    done < <(zsh "$launcher" --complete "${request[@]}" 2>/dev/null)
    local ret=1
    if (( ${#candidates} )); then compadd -V dotcmd -d descriptions -- "${candidates[@]}" && ret=0; fi
    if [[ -n $path_kind ]]; then
        [[ -z $before ]] || compset -p "${#before}"
        if [[ $path_kind == dotcmd:directory ]]; then _path_files -/ && ret=0
        else _path_files && ret=0; fi
    fi
    return $ret
}

if (( ! $+functions[compdef] )); then
    autoload -Uz compinit
    compinit
fi

_dotcmd_setup_colors() {
    zmodload zsh/complist || return
    local -a colors
    zstyle -a ':completion:*:default' list-colors colors
    local spec
    for spec in "${colors[@]}"; do
        [[ $spec == '(dotcmd)=(#b)(*)  (*)=0=1=2' ]] && return
    done
    zstyle ':completion:*:default' list-colors \
        '(dotcmd)=(#b)(*)  (*)=0=1=2' \
        '(dotcmd)=(#b)(*)=0=1' \
        "${colors[@]}"
}
_dotcmd_setup_colors
unfunction _dotcmd_setup_colors

compdef _dotcmd_complete .cmd
